#!/usr/bin/env bash

[[ "${CLOJARS_USERNAME}" = ""  ]] && { echo >&2 "CLOJARS_USERNAME has to be set"; exit 1; }
[[ "${CLOJARS_PASSWORD}" = ""  ]] && { echo >&2 "CLOJARS_PASSWORD has to be set"; exit 1; }

# Increment the patch level of the version tag, generate a new pom.xml with the
# new version, and create a git tag based on that commit
clojure -A:garamond patch --tag --pom --scm-url "https://github.com/smogg/re-promise"

# build uberjar
clj -A:pack

# deploy to clojars
clj -A:deploy
